openapi: 3.0.1
info:
  title: SubscriptMngmtAPI
  description: This api is used to connect to the ballerina service
  version: 1.0.0
servers:
  - url: /company
security:
  - default: []
paths:
  /users:
    get:
      parameters:
        - name: userName
          in: query
          required: true
          style: form
          explode: true
          schema:
            type: string
      responses:
        '200':
          description: ok
  

