openapi: 3.0.1
info:
  title: SubscriptionManagerAPI
  description: This api is used to connect to the ballerina service
  version: 1.0.0
servers:
  - url: /company
security:
  - default: []
paths:
  /users:
    get:
      parameters:
        - name: userName
          in: query
          required: true
          style: form
          explode: true
          schema:
            type: string
      responses:
        '200':
          description: ok
  /user:
    post:
      description: 'update an existing user '
      operationId: updateUser
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              type: object
        required: true
      responses:
        '200':
          description: ok
    post:
      description: 'create a new user '
      operationId: createUser
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              type: object
        required: true
      responses:
        '200':
          description: ok
    delete:
      parameters:
        - name: userName
          in: query
          required: true
          style: form
          explode: true
          schema:
            type: string
      responses:
        '200':
          description: ok


