openapi: 3.0.1
info:
  title: SubscriptionManagerAPI
  description: This api is used to connect to the ballerina service
  version: 1.0.0
servers:
  - url: /company
security:
  - default: []
paths:
  /users:
    get:
      parameters:
        - name: userName
          in: query
          required: true
          style: form
          explode: true
          schema:
            type: string
      responses:
        '200':
          description: ok
  /user:
    put:
      requestBody:
        description: 'Update a user'
        operationId: updateUser
        requestBody:
          description: Update an exist user 
          content:
            application/json:
            application/xml:
        required: true
      responses:
        '200':
          description: ok
    post:
      requestBody:
        description: 'Create a user'
        operationId: createUser
        requestBody:
          description: Create an new user 
          content:
            application/json:
            application/xml:
        required: true
      responses:
        '200':
          description: ok
    delete:
      parameters:
        - name: userName
          in: query
          required: true
          style: form
          explode: true
          schema:
            type: string
      responses:
        '200':
          description: ok


